unique_ids:
  assets:
    standard-page.html: 4CQK7S7XBNR642Z7XPXR3I7QWKVDJET6
    theme.css: VEBZQILDN7J43GPWJZUX5JQ6ORZN6DQP
  forms:
    Form1: KFNHDCJK3YDGQSWLCBJUYZNCSCMIVN5K
  modules: {}
  scripts: {}
  server_modules: {}
